version: '3'
services:
  manage_app:
    image: manage_app
    container_name: manage_app
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
      args:
        API_ONLY: 1
    volumes:
      - ./storage:/home/app/storage
      - ./log:/home/app/log
    environment:
      RAILS_MAX_THREADS: 5
      RAILS_MIN_THREADS: 1
      WEB_CONCURRENCY: 5
      HOST: 'http://0.0.0.0'
      PG_HOST: postgres
  manage_web:
    image: manage_web
    container_name: manage_web
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
      args:
        APP_NAME: manage_app
        APP_HOST: manage_app
    depends_on:
      - manage_app
    ports:
      - 80:80
  postgres:
    image: postgres:13.2
    container_name: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=6GB"
      - "-c"
      - "work_mem=128MB"
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '!~!manage2022!@!@!manage!~!'